name: lenden_delivery
description: Lenden Delivery Application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ====================== Development Packages ======================
  # State management
  provider: ^5.0.0
  get_it: ^7.1.3
  # Remote API
  data_connection_checker: ^0.3.4
  dio: ^4.0.0

  # Environment
  flutter_config: ^2.0.0
  # Testing
  mockito: ^5.0.13
  # Local cache
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.6
  # validation
  email_validator: ^1.0.6
  # launch
  # flutter_appavailability:
  #   git:
  #     url: "https://github.com/bwhiteTP/flutter_appavailability.git"
  #     ref: "26461d5296cd8c0a58da1d9c5f1e960643ebb323"
  launch_review: ^3.0.1
  # intents
  url_launcher: ^6.0.9
  #geo location
  geolocator: ^7.4.0
  # maps
  google_maps_flutter: ^2.0.6
  # qr code
  barcode_scan2: ^4.1.4
  # picker
  image_picker: ^0.8.2
  # encryption
  encrypt: ^5.0.0
  tuple: ^2.0.0
  crypto: ^3.0.1

  # ====================== UI Packages ======================
  # cache image
  cached_network_image: ^3.1.0
  # loading spinner
  flutter_spinkit: ^5.0.0
  # icons
  font_awesome_flutter: ^9.1.0
  cupertino_icons: ^1.0.3
  # date
  intl: ^0.17.0
  # timeline
  timeline_tile: ^2.0.0
  # charts
  charts_flutter: ^0.11.0
  # splash
  flare_splash_screen: ^4.0.0
  # lottie
  lottie: ^1.1.0
  # signature
  signature: ^4.1.1
  # save files
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # parsing json
  build_runner: ^2.1.0
  json_serializable: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/Graphik-Light.otf
          weight: 300
        - asset: assets/fonts/Graphik-Regular.otf
          weight: 400
        - asset: assets/fonts/Graphik-Medium.otf
          weight: 500
        - asset: assets/fonts/Graphik-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Graphik-Bold.otf
          weight: 700
        - asset: assets/fonts/Graphik-HardBold.otf
          weight: 900
        - asset: assets/fonts/Graphik-Italic.otf
          style: italic
